apiVersion: v1
kind: Service
metadata:
  name: service-nodesafeapp
  labels:
    servicelabel: nodesafeappservice
spec:
  ports:
    - port: 3333
      targetPort: 1111
  selector:
    apptemplate: template-nodesafeapp